version: '3'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/1
      - DATABASE_URI=sqlite:///database.db
  redis:
    image: redis:alpine
